name: Pages Deploy

# on:
#   push:
#     branches:
#       - main
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm i

      - name: Install subdirectory dependencies
        run: |
          npm run install-all

      - name: Build
        run: |
          pwd
          ls
          ls nuxtjs-project
          npm run build-all

      # - name: Copy files to docs directory
      #   run: |
      #     mkdir -p docs
      #     cp -R build/* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs